### ISSUE TITLE
name

### ISSUE THREAD

**Issue by jamesdbrock** [cdepillabout/purescript2nix#22]
I think this project needs a better name than `purescript2nix`. A name which says that this is an alternative to and replacement for the `spago` build system, written in Nix.

The name `purescript2nix` makes this project sound like `spago2nix`, `npm2nix`, `poetry2nix`, `yarn2nix`, et cetera. This project is not like those others, which are impure programs that query the internet and output a `.nix` file.

I think the name does not have to be short, because the name will not be a shell command in the same way that `spago` is a shell command?

`spagnix`? `spangix`?

We also have `purescript-compile`. Which is a shell command wrapper for `purs compile`. Is that a good name?

**Comment by cdepillabout** [comment]
> The name purescript2nix makes this project sound like spago2nix, npm2nix, poetry2nix, yarn2nix, et cetera. This project is not like those others, which are impure programs that query the internet and output a .nix file.

Some of the `*2nix` programs are impure (that is, they require access to the internet in a non-FOD), and some of them are pure.  For instance, `poetry2nix`, `stacklock2nix`, and `cabal2nix` (at least as it is used in Nixpkgs), are all pure, since they work with already-existing lock files.

> A name which says that this is an alternative to and replacement for the spago build system, written in Nix.

When originally writing `purescript2nix`, I didn't really intend `purescript2nix` to be an _alternative_ to spago, but more to be a way to build a PureScript project with Nix (mainly for use in CI, in a larger, Nix-based build system).  So in general developers would use continue to use `spago` for day-to-day development, and then only use `purescript2nix` when building in CI. (That's in contrast to a project like [`purs-nix`](https://github.com/purs-nix/purs-nix), which intends to completely replace usage of `spago` altogether, even for day-to-day development.)

I had originally wanted to call this library `spago2nix`, because it is a Nix library for building a project from a `spago.dhall` file.  But I didn't want to cause confusion with Justin's `spago2nix` project, so I went with `purescript2nix`.  `purescript2nix` goes against pattern laid-down by `cabal2nix`, `poetry2nix`, etc, but the good thing about it is that it is at least easy to understand.  Any Nix user looking for a way to build a PureScript package with Nix will see the name `purescript2nix` and immediately know what it does.

**Comment by jamesdbrock** [comment]
Okay you like the name and you want to keep it.

**Comment by jamesdbrock** [comment]
> this is an alternative to and replacement for the `spago` build system, written in Nix.

That was poorly phrased, I should have said “replacement for the `spago` executable in the spago build system.” Which is my understanding of what this project has become.

It’s a Nix function which takes a `spago.yaml` and a `src/` and produces a built PureScript package, without any dependency on the `spago` executable. Right?

**Comment by cdepillabout** [comment]
> Okay you like the name and you want to keep it.

Ah, sorry, I wasn't necessarily saying that it should be kept!  I was just explaining my thought-process that went into the name originally.

I do think that `purescript2nix` is a nice name, since it is immediately understandable to people in the Nix ecosystem.  But if you guys want to call it something else (to emphasize the fact that it _is_ a direct competitor to `spago`, and not just a library to use with `nix-build`), then let's do that!  I'm completely fine with changing the name of this repo, or transfering this repo to a separate organization or anything.

> It’s a Nix function which takes a spago.yaml and a src/ and produces a built PureScript package [by running `nix-build`], without any dependency on the spago executable. Right?

Originally this is what it was. (Although I had [wanted to use `spago` internally](https://github.com/cdepillabout/purescript2nix/issues/3), just to make the everyday experience of building with `spago` more similar to building with `nix-build`.)  Although it sounds like now there is also the `purescript-compile` function, which _is_ a direct competitor to `spago`?

If you guys wanted to emphasize the `purescript-compile` functionality, then renaming could be a good idea.
